services:
  - type: web
    name: statsdecision
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn statsdecision.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: statsdecisiondb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "0"