# Generated by Django 5.2 on 2025-04-09 23:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('organisateur', models.CharField(max_length=255)),
                ('type_evenement', models.CharField(choices=[('Conférence', 'Conférence'), ('Réunion', 'Réunion'), ('Formation', 'Formation'), ('Autre', 'Autre')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_evenements/')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantLinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='fas fa-link', max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie de lien',
                'verbose_name_plural': 'Catégories de liens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('consentement', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='statsdecision_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de clics')),
                ('last_clicked', models.DateTimeField(blank=True, null=True, verbose_name='Dernier clic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsdecision_app.importantlinkcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Lien important',
                'verbose_name_plural': 'Liens importants',
                'ordering': ['-is_featured', 'title'],
                'indexes': [models.Index(fields=['title'], name='statsdecisi_title_bbbc93_idx'), models.Index(fields=['category'], name='statsdecisi_categor_58e2d7_idx'), models.Index(fields=['is_featured'], name='statsdecisi_is_feat_3688c3_idx')],
            },
        ),
    ]
